### ISSUE TITLE
Generate a wrong proof

### ISSUE THREAD

**Issue by clarck7gmailcom** [olivmath/merkly#8]
**Describe the bug**
The proof is '[961, fc6]', which is not in the tree.

I provided 2 wallet addresses:
wallet = [
 '0x5ff...54e',
 '0x6fb...942',
]

The code is:
wallet_list = [wallet]
mtree = mtree(wallet_list)  # build merkle tree by lib 'merkly'
root = mtree.root    # calculate root
leaf = mtree.leafs   # calculate leafs
proof = mtree.proof(wallet[0])  # print the first wallet address in the wallet list
print('root', root,
          'leaf', leaf,
          'proof[0]', proof,
          )

the output is :
root : 
a3ea60c74884e4d8976733e90e586bc56bf738c18c23208b2c4bab42fcc07d10 

leaf:
['96120f2536c0e6873e22a4a4c21d8befd3a60a6a04fc0e840c0afee70b38eb36', 'fc669afbb2103e999115554ddba4fabb9d1ea650308c91c143348ca89cb7c256']

proof:  # Why the proof is this? I'm very confused.
[961, fc6]

**Comment by olivmath** [comment]
This happens because when you are printing in the terminal, you have a `list` of `Node` but when a class is printed python calls the `__repr__` method and in this method `Node` only shows a hash abbreviation, but you can operate normally.
```py
proof: # Why the proof is this? I'm very confused.
[961, fc6]
```

**Comment by clarck7gmailcom** [comment]
Thanks, Lucas, it works!
